#!/bin/bash   
echo -e "#!/bin/bash \nfind . -name "*.js" -type f -delete" >> 10-no_more_js

echo -e "#!/bin/bash \nls -la | grep '^d' | wc -l" >> 11-directories

echo -e "#!/bin/bash \nls -t | head -10" >> 12-newest_files

echo -e "#!/bin/bash \nsort | uniq -u" >> 13-unique

echo -e "#!/bin/bash \ngrep root /etc/passwd" >> 14-findthatword

echo -e "#!/bin/bash \ngrep bin /etc/passwd | wc -l" >> 15-countthatword

echo -e "#!/bin/bash \ngrep root -A 3 /etc/passwd" >> 16-whatsnext

echo -e "#!/bin/bash \ngrep -v bin /etc/passwd" >> 17-hidethisword

echo -e "#!/bin/bash \ngrep ^[a-z] -i /etc/ssh/sshd_config" >> 18-letteronly

echo -e "#!/bin/bash \nperl -pie "s/a/z/g"; "s/c/e/g" >> 19-AZ

echo -e "#!/bin/bash \ntr -d 'cC' " >> 20-hiago

echo -e "#!/bin/bash \nrev" >> 21-reverse

echo -e "#!/bin/bash \ncut -d: -f1,6 | sort -k6" >> 22-users_and_homes
