#!/bin/bash   
echo -e "#!/bin/bash \necho "Hello" $USER" >> 1-hello_you
                                                                                                                                  
echo -e "#!/bin/bash \nexport PATH=$PATH:/action" >> 2-path

echo -e "#!/bin/bash \nDIR=$(find . -type d)" >> 3-paths

echo -e "#!/bin/bash \nprintenv" >> 4-global_variables

echo -e "#!/bin/bash \nset" >> 5-local_variables

echo -e "#!/bin/bash \nBETTY="Holberton"" >> 6-create_local_variable

echo -e "#!/bin/bash \nexport HOLBERTON=Betty" >> 7-create_global_variable

echo -e "#!/bin/bash \necho $((TRUEKNOWLEDGE+128))" >> 8-true_knowledge

echo -e "#!/bin/bash \necho $((POWER/DIVIDE))" >> 9-divide_and_rule

echo -e "#!/bin/bash \necho $((BREATH**LOVE))" >> 10-love_exponent_breath

echo -e "#!/bin/bash \necho printf "%2f" $NUM" >> 13-print_float